# Server
server.port=8080

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/gatepass_db
spring.datasource.username=postgres
spring.datasource.password=root123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=gatepass_jwt_secret_key_change_in_production_2024
jwt.expiration=604800000

# Logging
logging.level.com.gatepass=DEBUG
logging.level.org.springframework.security=INFO

# CORS
spring.web.cors.allowed-origins=http://localhost:3000

# Jackson - camelCase JSON + ignore lazy load errors
spring.jackson.property-naming-strategy=LOWER_CAMEL_CASE
spring.jackson.serialization.fail-on-empty-beans=false
spring.jackson.serialization.write-dates-as-timestamps=false
